# Generated by Django 3.1.7 on 2021-03-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256, verbose_name='rua')),
                ('number', models.IntegerField(verbose_name='número')),
                ('neighborhood', models.CharField(max_length=90, verbose_name='bairro')),
                ('complement_address', models.CharField(max_length=256, verbose_name='complemento')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nome')),
                ('company_name', models.CharField(max_length=90, verbose_name='razão social')),
                ('cnpj', models.IntegerField(verbose_name='cnpj')),
                ('email', models.CharField(max_length=256, verbose_name='e-mail de contato')),
                ('telephone', models.IntegerField(verbose_name='telefone de contato')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('update_at', models.DateField(auto_now=True, verbose_name='data de atualização')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesperson.address', verbose_name='endereço')),
            ],
        ),
    ]
