# Generated by Django 3.1.7 on 2021-03-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='nome')),
                ('description', models.CharField(max_length=256, verbose_name='descrição')),
                ('site', models.CharField(max_length=256, verbose_name='site')),
                ('telephone', models.IntegerField(verbose_name='telefone de contato')),
                ('email', models.CharField(max_length=256, verbose_name='e-mail de contato')),
                ('support_contact', models.CharField(max_length=256, verbose_name='contato responsável técnico')),
            ],
        ),
    ]
